version: '3.8'

services:
  api-gateway:
    image: bow-meow-api-gateway:latest # API Gateway의 Docker 이미지
    ports:
      - "80:80"  # API Gateway의 외부 포트
    depends_on:
      - product-service
      - payment-service
    environment:
      - API_GATEWAY_ENV=production
    networks:
      - bow-meow-network

  product-service:
    image: bow-meow-product:latest # product Docker 이미지
    ports:
      - "8083:8080"  # Product 서비스의 외부 포트
    environment:
      - SERVICE_ENV=production
      - DB_HOST=bow-meow-product-db
      - DB_USER=bow-meow-product-user
      - DB_PASSWORD=bow-meow-product-pass-word
      - DB_NAME=bow-meow-product_db
    depends_on:
      - bow-meow-product-db
    networks:
      - bow-meow-network

  payment-service:
    image: bow-meow-payment:latest  # payment Docker 이미지
    ports:
      - "8082:8080"  # Payment 서비스의 외부 포트
    environment:
      - SERVICE_ENV=production
      - DB_HOST=bow-meow-payment-db
      - DB_USER=bow-meow-payment-user
      - DB_PASSWORD=bow-meow-payment-pass-word
      - DB_NAME=bow-meow-payment_db
    depends_on:
      - bow-meow-payment-db
    networks:
      - bow-meow-network

  bow-meow-product-db:
    image: mysql:latest  # product 데이터베이스
    environment:
      MYSQL_USER: bow-meow-product-user # user
      MYSQL_PASSWORD: bow-meow-product-pass-word # password
      MYSQL_DATABASE: bow-meow-product_db # db
    volumes:
      - bow-meow-product-db-data:/var/lib/mysql/data
    networks:
      - bow-meow-network

  bow-meow-payment-db:
    image: postgres:latest  # payment 데이터베이스
    environment:
      POSTGRES_USER: bow-meow-payment-user # user
      POSTGRES_PASSWORD: bow-meow-payment-pass-word # password
      POSTGRES_DB: bow-meow-payment_db # db
    volumes:
      - bow-meow-payment-db-data:/var/lib/postgresql/data
    networks:
      - bow-meow-network

volumes:
  bow-meow-product-db-data:
  bow-meow-payment-db-data:

networks:
  bow-meow-network:
