services:
  api-gateway:
    image: bow-meow-api-gateway:latest
    ports:
      - "80:80"
    depends_on:
      - mysql-db
    networks:
      - bow-meow-network

  product-service:
    image: bow-meow-product:latest
    ports:
      - "8083:8080"
    environment:
      - SERVICE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=product_db
    depends_on:
      - mysql-db
    networks:
      - bow-meow-network

  payment-service:
    image: bow-meow-payment:latest
    ports:
      - "8082:8080"
    environment:
      - SERVICE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=payment_db
    depends_on:
      - mysql-db
    networks:
      - bow-meow-network

  user-service:
    image: bow-meow-user:latest
    ports:
      - "8081:8080"
    environment:
      - SERVICE_ENV=production
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user_db
    depends_on:
      - mysql-db
      - redis
    networks:
      - bow-meow-network

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql  # 초기화 스크립트 마운트
    networks:
      - bow-meow-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - bow-meow-network

volumes:
  mysql-db-data:

networks:
  bow-meow-network:
