spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: bowmeow_member_service
          uri: http://localhost:8081/
          predicates:
            - Path=/members/**
        - id: bowmeow_payment_service
          uri: http://localhost:8082/
          predicates:
            - Path=/payments/**
          filters:
            - name: AuthFilter # JWT 토큰 비교
        - id: bowmeow_product_service
          uri: http://localhost:8083/
          predicates:
            - Path=/products/**
          filters:
            - name: AuthFilter # JWT 토큰 비교
        - id: bowmeow_basket_service
          uri: http://localhost:8084/
          predicates:
            - Path=/baskets/**
          filters:
            - name: AuthFilter # JWT 토큰 비교
        - id: bowmeow_review_service
          uri: http://localhost:8085/
          predicates:
            - Path=/reviews/**
          filters:
            - name: JwtAuthenticationFilter # JWT 토큰 비교

